name: Run SageMath Doctests

on: [push, pull_request]

jobs:
  doctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # This ensures that submodules are recursively initialized and updated

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull SageMath Docker image
        run: docker pull sagemath/sagemath:latest

      - name: Run doctests
        run: |
          docker run --rm -v ${{ github.workspace }}:/mnt/sage sagemath/sagemath:latest /bin/bash -c "
            cd /mnt/sage &&
            export PYTHONPATH=.:$PYTHONPATH &&
            sage --version &&
            find . -name '*.py' -print0 | xargs -0 sage -t"